In [28]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:85% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:12pt;}
div.output {font-size:10pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:80px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:2px;}
table.dataframe{font-size:22px;}
</style>
"""))

<font size="6" color="green"><b>ch14. 웹 데이터 수집</b></font>
# 1절. Beautifulsoup와 parser
    (정적 웹크롤링, 공공 api 사용)
    
`pip install bs4` 아나콘다를 설치하면 자동 설치되는 패키지에 포함 
<br>
▪ 공식 사이트 : https://www.crummy.com/software/BeautifulSoup/
<br>
▪ Documentation : https://www.crummy.com/software/BeautifulSoup/bs4/doc/

In [15]:
import requests # HTTP요청 처리하는 lib
# file:// == c:
# http://www.
from requests_file import FileAdapter

In [16]:
# 로컬에 있는 파일을 웹요청하듯이 읽어오는 작업
s = requests.Session()
s.mount("file://", FileAdapter()) # fill://로 시작한느 url을 어뎁터가 처리
response = s.get("file:///ai/lecNote/01_python/data/ch14_sample.html") # c:/ai/lecNote/data/ch14_sample.html
response

In [19]:
if response:
    print('해당 url에 접근함')
else:
    print('해당 url에 거부됨')

해당 url에 접근함

In [21]:
response.status_code
# 200 : 정상
# 404 : 없는 페이지

200

In [24]:
response.content # html의 바리너리 형식의 내용

b'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90 \xec\x95\x88\xec\x9d\x98 \xeb\x82\xb4\xec\x9a\xa9</div>\r\n  <p>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90\xec\x84\x9c \xed\x99\x9c\xec\x9a\xa9\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</p>\r\n  <div class="contents">\r\n    \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\xa5\xbc \xec\x96\xb4\xeb\x96\xbb\xea\xb2\x8c \xec\x9e\x91\xec\x84\xb1\xed\x95\x98\xeb\x8a\x90\xeb\x83\x90\xec\x97\x90 \xeb\x94\xb0\xeb\x9d\xbc\r\n    <span>\xeb\x8b\xa4\xeb\xa5\xb8<b>\xec\x9a\x94\xec\x86\x8c\xea\xb0\x80 \xeb\xb0\x98\xed\x99\x98</b></span>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4\r\n  </div>\r\n  <div>CSS \xec\x84\xa0\xed\x83\x9d\xec\x9e\x90\xeb\x8a\x94 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xea\xb3\xb3\xec\x97\x90 <b>\xed\x99\x9c\xec\x9a\xa9</b>\xeb\x90\xa9\xeb\x8b\x88\xeb\x8b\xa4</div>\r\n</body>\r\n</html>'

In [25]:
print(response.content.decode('utf-8'))

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
</head>
<body>
  <h1 class="greeting css" id="text">Hello, CSS</h1>
  <h1 class="css">Hi, CSS</h1>
  <div id="subject">subject 선택자 안의 내용</div>
  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>
  <div class="contents">
    선택자를 어떻게 작성하느냐에 따라
    <span>다른<b>요소가 반환</b></span>됩니다
  </div>
  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>
</body>
</html>

In [26]:
response.text

'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n</head>\r\n<body>\r\n  <h1 class="greeting css" id="text">Hello, CSS</h1>\r\n  <h1 class="css">Hi, CSS</h1>\r\n  <div id="subject">subject 선택자 안의 내용</div>\r\n  <p>CSS 선택자는 다양한 곳에서 활용됩니다</p>\r\n  <div class="contents">\r\n    선택자를 어떻게 작성하느냐에 따라\r\n    <span>다른<b>요소가 반환</b></span>됩니다\r\n  </div>\r\n  <div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>\r\n</body>\r\n</html>'

In [29]:
#html 파싱 객체
from bs4 import BeautifulSoup
soup = BeautifulSoup(response.text, # == response.content,
                    "html.parser")
# soup.__str__()
# soup

<!DOCTYPE html>

<html lang="en">
<head>
<meta charset="utf-8"/>
</head>
<body>
<h1 class="greeting css" id="text">Hello, CSS</h1>
<h1 class="css">Hi, CSS</h1>
<div id="subject">subject 선택자 안의 내용</div>
<p>CSS 선택자는 다양한 곳에서 활용됩니다</p>
<div class="contents">
    선택자를 어떻게 작성하느냐에 따라
    <span>다른<b>요소가 반환</b></span>됩니다
  </div>
<div>CSS 선택자는 다양한 곳에 <b>활용</b>됩니다</div>
</body>
</html>

In [37]:
#soup.select_one('선택자') : 해당 선택자 처음 하나 엘리먼트만
el = soup.select_one('h1.greeting.css')
print('el =', el)
print('el.text = ', el.text)
print('el.string = ', el.string)
print('el의 속성들 = ', el.attrs)
print('el의 class속성 = ', el.attrs['class'])
print('el의 class속성 = ', el.attrs.get('class'))
# print('el의 href속성 = ', el.attrs.get['href'])
print('el의 href속성 = ', el.attrs.get('href'))
print('el의 name = ', el.name)

el = <h1 class="greeting css" id="text">Hello, CSS</h1>
el.text =  Hello, CSS
el.string =  Hello, CSS
el의 속성들 =  {'class': ['greeting', 'css'], 'id': 'text'}
el의 class속성 =  ['greeting', 'css']
el의 class속성 =  ['greeting', 'css']
el의 href속성 =  None
el의 name =  h1

In [42]:
# 2. soup.select('선택자') : 해당 선책자 엘리먼트 다 list로
els = soup.select('h1.css')
print('els =>', els)
print('els들의 text', [el.text for el in els])
print('els들의 string', [el.string for el in els])
print('els들의 속성들', [el.attrs for el in els])
print('els들의 class 속성', [el.attrs.get('class') for el in els])

els => [<h1 class="greeting css" id="text">Hello, CSS</h1>, <h1 class="css">Hi, CSS</h1>]
els들의 text ['Hello, CSS', 'Hi, CSS']
els들의 string ['Hello, CSS', 'Hi, CSS']
els들의 속성들 [{'class': ['greeting', 'css'], 'id': 'text'}, {'class': ['css']}]
els들의 class 속성 [['greeting', 'css'], ['css']]

In [46]:
#3. soup.find(태그, 속성) vs soup.select_one('선택자') : 해당 속성을 갖은 태그. 처음 하나만
print('select_one :', soup.select_one('h1.css'))
print('find       :', soup.find('h1', {'class':'css'}))
print('find       :', soup.find('h1', class_='css'))
print()
print('select_one :', soup.select_one('h1#text'))
print('select_one :', soup.select_one('h1', {'id':'text'}))

select_one : <h1 class="greeting css" id="text">Hello, CSS</h1>
find       : <h1 class="greeting css" id="text">Hello, CSS</h1>
find       : <h1 class="greeting css" id="text">Hello, CSS</h1>

select_one : <h1 class="greeting css" id="text">Hello, CSS</h1>
select_one : <h1 class="greeting css" id="text">Hello, CSS</h1>

In [53]:
# 4. soup.find_all(태그, 속성) vs soup.select_one('선택자') : 해당 엘리먼트 다 list로
print('모든 h1.css와 span태그 :', soup.select('h1.css, span'))
print('모든 h1.css와 span태그 :', soup.find_all(['h1'], class_=('css') + soup.find_all('span'))

SyntaxError: incomplete input (4136789065.py, line 3)

In [60]:
# 없는 엘리먼트 찾기
print('find_all(빈list) :', soup.find_all('a'))
print('find(None) :', soup.find('a'))
print('select(빈list) :', soup.select('a'))
print('select_one(None) :', soup.select_one('a'))

find_all(빈list) : []
find(None) : None
select(빈list) : []
select_one(None) : None

# 2절. 정적 웹 데이터 수집(정적 웹크롤링)
## 2.1 BeautifulSoup 모듈을 활용한 html 웹 데이터 수집
### 1) 환율 정보 가져오기(네이버증권>시장지표)

- https://finance.naver.com/marketindex/
    * 크롤링 허용범위는 사이트마다 ~/robots.txt에서 확인할 수 있음
        - Allow : 크롤링 허용가능한 폴더
        - Disallow : 크롤링 제한 폴더

In [63]:
# soup 객체 생성 방법 1
import requests
from bs4 import BeautifulSoup
url ='https://finance.naver.com/marketindex/'
requests = requests.get(url)
#requests #Response
print(response.status_code)
# response.text # response.content
soup = BeautifulSoup(response.text, 'html.parser')

200

In [71]:
# soup 객체 생성 방법 2
from urllib.request import urlopen
url = 'https://finance.naver.com/marketindex/'
response = urlopen(url)
# response
print(response.status)
# print(response.read().decode('cp949'))
soup = BeautifulSoup(response, 'html.parser')

200

In [85]:
p = '1,470.70'
float(p.replace(',', '')) # 방법 1
float(''.join(p.split(','))) # 방법2

1470.7

In [89]:
# div.head_info 밑의 span.value (find계열)
prices = []
headinfos = soup.find_all('div', class_='head_info')
for headinfo in headinfos:
    # print(headinfos)
    price = headinfo.find('span', class_='value')
    prices.append(float(''.join(price.text.split(','))))
print(prices)

[1415.9, 887.99, 1633.31, 209.83, 159.24, 1.1541, 1.3507, 99.71, 83.2, 1863.92, 4441.1, 200543.23]

In [92]:
# span.value (find 계열)
price_els = soup.find_all('span', class_='value')
prices = [round(float(price.text.replace(',', '')), 1) for price in price_els]
print(prices)

[1415.9, 888.0, 1633.3, 209.8, 159.2, 1.2, 1.4, 99.7, 83.2, 1863.9, 4441.1, 200543.2]

In [93]:
# div.head_info 밑의 span.value
price_els = soup.select('div.head_info > span.value')
# price_els

[<span class="value">1,415.90</span>,
 <span class="value">887.99</span>,
 <span class="value">1,633.31</span>,
 <span class="value">209.83</span>,
 <span class="value">159.2400</span>,
 <span class="value">1.1541</span>,
 <span class="value">1.3507</span>,
 <span class="value">99.7100</span>,
 <span class="value">83.2</span>,
 <span class="value">1863.92</span>,
 <span class="value">4441.1</span>,
 <span class="value">200543.23</span>]

In [98]:
title_els = soup.select('h3.h_lst >span.blind')
# title_els

[<span class="blind">미국 USD</span>,
 <span class="blind">일본 JPY(100엔)</span>,
 <span class="blind">유럽연합 EUR</span>,
 <span class="blind">중국 CNY</span>,
 <span class="blind">달러/일본 엔</span>,
 <span class="blind">유로/달러</span>,
 <span class="blind">영국 파운드/달러</span>,
 <span class="blind">달러인덱스</span>,
 <span class="blind">WTI</span>,
 <span class="blind">휘발유</span>,
 <span class="blind">국제 금</span>,
 <span class="blind">국내 금</span>]

In [102]:
# 단위들 : div.head_info > span > span.blind
unit_els = soup.select('div.head_info > span > span.blind')
len(unit_els)
units = [unit_el.string for unit_el in unit_els]
units.insert(7,'')
units

['원', '원', '원', '원', '엔', '달러', '달러', '', '달러', '원', '달러', '원']

In [105]:
# 상승 / 하락 div.head_info > span.blind
trend_els = soup.select('div.head_info > span.blind')
trend_els

[<span class="blind">상승</span>,
 <span class="blind">상승</span>,
 <span class="blind">상승</span>,
 <span class="blind">상승</span>,
 <span class="blind">상승</span>,
 <span class="blind">하락</span>,
 <span class="blind">하락</span>,
 <span class="blind">상승</span>,
 <span class="blind">상승</span>,
 <span class="blind">하락</span>,
 <span class="blind">상승</span>,
 <span class="blind">상승</span>]

In [106]:
for title, price, unit, trend in zip(title_els, price_els, units, trend_els):
    print("{} : {}{} - {}".format(title.text, price.text, unit, trend.text))

미국 USD : 1,415.90원 - 상승
일본 JPY(100엔) : 887.99원 - 상승
유럽연합 EUR : 1,633.31원 - 상승
중국 CNY : 209.83원 - 상승
달러/일본 엔 : 159.2400엔 - 상승
유로/달러 : 1.1541달러 - 하락
영국 파운드/달러 : 1.3507달러 - 하락
달러인덱스 : 99.7100 - 상승
WTI : 83.2달러 - 상승
휘발유 : 1863.92원 - 하락
국제 금 : 4441.1달러 - 상승
국내 금 : 200543.23원 - 상승

In [109]:
import pandas as pd
data = []
for title, price, unit, trend in zip(title_els, price_els, units, trend_els):
    data.append({'title' : title.text,
                'price' : float(price.text.replace(',', '')),
                'unit' : unit,
                'trend' : trend.text})
pd.DataFrame(data) #.to_csv('data/file.csv', index=false)

           title        price unit trend
0         미국 USD    1415.9000    원    상승
1   일본 JPY(100엔)     887.9900    원    상승
2       유럽연합 EUR    1633.3100    원    상승
3         중국 CNY     209.8300    원    상승
4        달러/일본 엔     159.2400    엔    상승
5          유로/달러       1.1541   달러    하락
6      영국 파운드/달러       1.3507   달러    하락
7          달러인덱스      99.7100         상승
8            WTI      83.2000   달러    상승
9            휘발유    1863.9200    원    하락
10          국제 금    4441.1000   달러    상승
11          국내 금  200543.2300    원    상승

In [112]:
data = []
for title, price, unit, trend in zip(title_els, price_els, units, trend_els):
    data.append([title.text, float(price.text.replace(',', '')), unit, trend.text])
pd.DataFrame(data, columns=['title', 'price', 'unit', 'trend'])

           title        price unit trend
0         미국 USD    1415.9000    원    상승
1   일본 JPY(100엔)     887.9900    원    상승
2       유럽연합 EUR    1633.3100    원    상승
3         중국 CNY     209.8300    원    상승
4        달러/일본 엔     159.2400    엔    상승
5          유로/달러       1.1541   달러    하락
6      영국 파운드/달러       1.3507   달러    하락
7          달러인덱스      99.7100         상승
8            WTI      83.2000   달러    상승
9            휘발유    1863.9200    원    하락
10          국제 금    4441.1000   달러    상승
11          국내 금  200543.2300    원    상승

### 2) 이번주 로또번호 출력
- 방법 2에서 user Agent를 추가하여 soup생성
- https://search.daum.net/search?w=tot&DA=YZR&t__nil_searchbox=btn&q=lotto (다음에서 lotto검색)
```
1236(2026.08.08 추첨)
당첨번호 [12, 18,21, 29, 34, 38]
보너스 10
```

In [114]:
# 방법1
import requests
from bs4 import BeautifulSoup
url = 'https://search.daum.net/search?w=tot&DA=YZR&t__nil_searchbox=btn&q=lotto'
response = requests.get(url)
print('response의 상태 :' , response.status_code)
soup = BeautifulSoup(response.text, 'html.parser')
# soup

response의 상태 : 200

In [120]:
# 방법2
from urllib.request import urlopen, Request
headers = {'User-Agent':
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36'}
request = Request(url, headers =headers)

response = urlopen(request)
print('response의 상태 :', response.status)
soup = BeautifulSoup(response, 'html.parser')
# soup

response의 상태 : 200

In [149]:
# 1236회(2026.08.08 추첨)
# 당첨번호 [12, 18,21, 29, 34, 38]
# 보너스 10
times = soup.select_one('div.prize span.f_red').text
date = soup.select_one('div.prize > span.date').text
title1 = soup.select_one('div.prize > strong').text[-4:]
lotto_numbers = soup.select('div.lottonum > span.ball:nth-last-child(n+3)')
# lotto_numbers = soup.select('div.lottonum > span.ball')[2]
title2 = soup.select_one('div.lottonum span.screen_out').text
lotto_bonus = soup.select_one('div.lottonum > span.bg_ball1').text
print(times, date)
print(title1, [int(numbers.text) for numbers in lotto_numbers])
print(title2, lotto_bonus)

1236회 (2026.08.08 추첨)
당첨번호 [12, 18, 21, 29, 34, 38]
보너스 10

In [165]:
# 위의 select계열 함수를 find계열함수로 변경하여 구현해 보기
prize = soup.find('div', class_ = 'prize')
times = prize.find('span', class_ = 'f_red').text
date = prize.find('span', class_ = 'date').text
title1 = prize.find('strong').text[-4:]

lottonum = soup.find('div', class_ = 'lottonum')
Lotto_numbers = lottonum.find_all('span', class_='ball')[:-2]

                   
print(times, date)
print(title1, [int(numbers.text) for numbers in lotto_numbers])
print(title2, lotto_bonus)

1236회 (2026.08.08 추첨)
당첨번호 [12, 18, 21, 29, 34, 38]
보너스 10

### 3) DAUM 뉴스 검색 리스트
```
no title href
0 타이틀1 http://~~
1 타이틀2 http://~~
2 타이틀3 http://~~
```

In [168]:
# 방법1
import requests
from bs4 import BeautifulSoup
word = '금시세'
url = f'https://search.daum.net/search?w=news&q={word}'
print(url)
response = requests.get(url)
print(response.status_code)
soup = BeautifulSoup(response.text, 'html.parser')

https://search.daum.net/search?w=news&q=금시세
200

In [175]:
# 방법2
from urllib.request import urlopen, Request
from urllib.parse import quote
word = quote('금시세')
url = f'https://search.daum.net/search?w=news&q={word}'
print(url)
headers = {'User-Agent':
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36'}
# request = Request(url, headers=headers)
request =Request(url)
request.add_header('User-Agent', 
                   'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36')
response = urlopen(request)
print(response.status)
soup =BeautifulSoup(response, 'html.parser')
# soup

https://search.daum.net/search?w=news&q=%EA%B8%88%EC%8B%9C%EC%84%B8
200

In [183]:
items_find_list = [] # 검색한 결과를 담을 dict 리스트
items_el = soup.select('div.item-title > strong.tit-g.clamp-g > a')
for idx, item in enumerate(items_el):
    # print(idx, item)
    items_find_list.append({'no':idx + 1,
                           'title':item.text,
                           'link': item.attrs.get('href')})
import pandas as pd
pd.DataFrame(items_find_list)

   no                             title                                   link
0   1                       금시세(금값) 7일   http://v.daum.net/v/20260807091927501
1   2         [오늘 금시세]금값, 국내 내리고·국제 올라   http://v.daum.net/v/20260812091805335
2   3                     오늘 금시세(금값)는?   http://v.daum.net/v/20260810095337025
3   4   [오늘 금시세]호르무즈 해협 재개 기대감에 금값, 급등   http://v.daum.net/v/20260806091818372
4   5                      금시세(금값) 29일   http://v.daum.net/v/20260729100307412

In [185]:
items_find_list = [] # 검색한 결과를 담을 2차원 리스트
items_el = soup.select('div.item-title > strong.tit-g.clamp-g > a')
for idx, item in enumerate(items_el):
    items_find_list.append([idx, item.text, item.attrs.get('href')])
pd.DataFrame(items_find_list, columns=['순번', '기사제목', '링크'])

   순번                                        기사제목                                     링크
0   0                                 금시세(금값) 7일   http://v.daum.net/v/20260807091927501
1   1                   [오늘 금시세]금값, 국내 내리고·국제 올라   http://v.daum.net/v/20260812091805335
2   2                               오늘 금시세(금값)는?   http://v.daum.net/v/20260810095337025
3   3             [오늘 금시세]호르무즈 해협 재개 기대감에 금값, 급등   http://v.daum.net/v/20260806091818372
4   4                                금시세(금값) 29일   http://v.daum.net/v/20260729100307412
5   5                    [오늘 금시세]국내·국제 금값 모두 하락세   http://v.daum.net/v/20260724091819449
6   6   [오늘 금시세]중동 긴장 완화에 금값, 강보합…4천100달러선 회복 시도   http://v.daum.net/v/20260728091834427
7   7          [오늘 금시세]달러 약세에 금값, 반등…4천150달러선 회복   http://v.daum.net/v/20260723091827366
8   8             [금값시세] 8월 11일, 18K 14K 나란히 오름세   http://v.daum.net/v/20260811112707814
9   9      [오늘 금시세]저가 매수세 유입에 금값, 반등…4천달러선 지지 확인   http://v.daum.net/v/20260722092117388

In [192]:
# 다음 뉴스 검색 함수(원하는 키워드, 원하는 페이지 수 입력)
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def collect_list(keyword, page):
    'keyword로 해당 page에 검색한 결과 dict list return'
    # url = f'https://search.daum.net/search?w=news&q={keyword}&p={page}'
    url = f'https://search.daum.net/search?w=news'
    params = {'q':keyword, 'p':page}
    response = request.get(url, params=params)
    soup = BeautifulSoup(response.text, 'html.parser')
    items_find_list = []
    items_el = soup.select('div.item-title > strong.tit-g > a')
    for idx, item in enumerate(items_el):
        items_find_list.append({'no':(page-1)*10 + idx,
                               'title':item.text,
                               'link':item.attrs.get('href')})
    return items_find_list

In [193]:
collect_list('국립중앙박물관', 10)

AttributeError: 'Request' object has no attribute 'get'